"""Tabela CFOP — Código Fiscal de Operações e Prestações.

Fonte: Ajuste SINIEF / CONFAZ.
Organizada por faixa:
  1xxx = Entrada estadual      5xxx = Saída estadual
  2xxx = Entrada interestadual 6xxx = Saída interestadual
  3xxx = Entrada importação    7xxx = Saída exportação

Contém os CFOPs mais utilizados no varejo. A tabela completa possui ~600 códigos;
aqui estão os ~120 mais comuns para validação e sugestão.
"""

CFOP: dict[str, str] = {
    # ══════════════════════════════════════════════
    # ENTRADAS ESTADUAIS (1xxx)
    # ══════════════════════════════════════════════
    "1101": "Compra para industrialização",
    "1102": "Compra para comercialização",
    "1111": "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial",
    "1113": "Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil",
    "1116": "Compra para industrialização originada de encomenda para recebimento futuro",
    "1117": "Compra para comercialização originada de encomenda para recebimento futuro",
    "1120": "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente",
    "1121": "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente",
    "1122": "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador",
    "1124": "Industrialização efetuada por outra empresa",
    "1125": "Industrialização efetuada por outra empresa quando a mercadoria foi remetida pelo fornecedor",
    "1126": "Compra para utilização na prestação de serviço sujeita ao ICMS",
    "1128": "Compra para utilização na prestação de serviço sujeita ao ISSQN",
    "1151": "Transferência para industrialização",
    "1152": "Transferência para comercialização",
    "1153": "Transferência de energia elétrica para distribuição",
    "1154": "Transferência para utilização na prestação de serviço",
    "1201": "Devolução de venda de produção do estabelecimento",
    "1202": "Devolução de venda de mercadoria adquirida ou recebida de terceiros",
    "1203": "Devolução de venda de produção do estabelecimento destinada à Zona Franca de Manaus",
    "1204": "Devolução de venda de mercadoria adquirida destinada à Zona Franca de Manaus",
    "1208": "Devolução de produção do estabelecimento remetida em transferência",
    "1209": "Devolução de mercadoria adquirida remetida em transferência",
    "1251": "Compra de energia elétrica para distribuição",
    "1252": "Compra de energia elétrica por estabelecimento industrial",
    "1253": "Compra de energia elétrica por estabelecimento comercial",
    "1254": "Compra de energia elétrica por estabelecimento prestador de serviço de transporte",
    "1255": "Compra de energia elétrica por estabelecimento prestador de serviço de comunicação",
    "1256": "Compra de energia elétrica por estabelecimento de produtor rural",
    "1257": "Compra de energia elétrica para consumo por demanda contratada",
    "1301": "Aquisição de serviço de comunicação para execução de serviço da mesma natureza",
    "1302": "Aquisição de serviço de comunicação por estabelecimento industrial",
    "1303": "Aquisição de serviço de comunicação por estabelecimento comercial",
    "1352": "Aquisição de serviço de transporte por estabelecimento industrial",
    "1353": "Aquisição de serviço de transporte por estabelecimento comercial",
    "1401": "Compra para industrialização em operação com mercadoria sujeita ao regime de ST",
    "1403": "Compra para comercialização em operação com mercadoria sujeita ao regime de ST",
    "1406": "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de ST",
    "1407": "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de ST",
    "1408": "Transferência para industrialização em operação com mercadoria sujeita ao regime de ST",
    "1409": "Transferência para comercialização em operação com mercadoria sujeita ao regime de ST",
    "1410": "Devolução de venda de mercadoria com ST",
    "1411": "Devolução de venda de mercadoria com ST em operação com mercadoria sujeita ao regime de ST",
    "1414": "Retorno de mercadoria para venda remetida para estabelecimentos em regime de ST",
    "1501": "Entrada de mercadoria recebida com fim específico de exportação",
    "1503": "Entrada decorrente de devolução de produto remetido com fim específico de exportação",
    "1504": "Entrada decorrente de devolução de mercadoria remetida para formação de lote de exportação",
    "1551": "Compra de bem para o ativo imobilizado",
    "1552": "Transferência de bem do ativo imobilizado",
    "1553": "Devolução de venda de bem do ativo imobilizado",
    "1554": "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento",
    "1555": "Entrada de bem do ativo imobilizado de terceiro remetido para uso no estabelecimento",
    "1556": "Compra de material para uso ou consumo",
    "1557": "Transferência de material para uso ou consumo",
    "1601": "Recebimento, por transferência, de crédito de ICMS",
    "1602": "Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento",
    "1603": "Ressarcimento de ICMS retido por substituição tributária",
    "1604": "Lançamento de crédito referente à entrada de bem do ativo imobilizado",
    "1605": "Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento",
    "1651": "Compra de combustível para industrialização subsequente",
    "1652": "Compra de combustível para comercialização",
    "1653": "Compra de combustível para uso ou consumo",
    "1901": "Entrada para industrialização por encomenda",
    "1902": "Retorno de mercadoria remetida para industrialização por encomenda",
    "1903": "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo",
    "1904": "Retorno de remessa para venda fora do estabelecimento",
    "1905": "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral",
    "1906": "Retorno de mercadoria remetida para depósito fechado ou armazém geral",
    "1907": "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral",
    "1908": "Entrada de bem por conta de contrato de comodato",
    "1909": "Retorno de bem remetido por conta de contrato de comodato",
    "1910": "Entrada de bonificação, doação ou brinde",
    "1911": "Entrada de amostra grátis",
    "1912": "Entrada de mercadoria ou bem recebido para demonstração",
    "1913": "Retorno de mercadoria ou bem remetido para demonstração",
    "1914": "Retorno de mercadoria ou bem remetido para exposição ou feira",
    "1915": "Entrada de mercadoria ou bem recebido para conserto ou reparo",
    "1916": "Retorno de mercadoria ou bem remetido para conserto ou reparo",
    "1917": "Entrada de mercadoria recebida em consignação mercantil ou industrial",
    "1918": "Devolução de mercadoria remetida em consignação mercantil ou industrial",
    "1919": "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial remetida anteriormente em consignação",
    "1920": "Entrada de vasilhame ou sacaria",
    "1921": "Retorno de vasilhame ou sacaria",
    "1922": "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro",
    "1923": "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem",
    "1924": "Entrada para industrialização por conta e ordem do adquirente da mercadoria",
    "1925": "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente",
    "1926": "Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação",
    "1933": "Aquisição de serviço tributado pelo ISSQN",
    "1949": "Outra entrada de mercadoria ou prestação de serviço não especificada",

    # ══════════════════════════════════════════════
    # ENTRADAS INTERESTADUAIS (2xxx)
    # ══════════════════════════════════════════════
    "2101": "Compra para industrialização",
    "2102": "Compra para comercialização",
    "2111": "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial",
    "2113": "Compra para comercialização de mercadoria recebida anteriormente em consignação mercantil",
    "2116": "Compra para industrialização originada de encomenda para recebimento futuro",
    "2117": "Compra para comercialização originada de encomenda para recebimento futuro",
    "2120": "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente",
    "2121": "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente",
    "2122": "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador",
    "2124": "Industrialização efetuada por outra empresa",
    "2125": "Industrialização efetuada por outra empresa quando a mercadoria foi remetida pelo fornecedor",
    "2126": "Compra para utilização na prestação de serviço sujeita ao ICMS",
    "2128": "Compra para utilização na prestação de serviço sujeita ao ISSQN",
    "2151": "Transferência para industrialização",
    "2152": "Transferência para comercialização",
    "2153": "Transferência de energia elétrica para distribuição",
    "2154": "Transferência para utilização na prestação de serviço",
    "2201": "Devolução de venda de produção do estabelecimento",
    "2202": "Devolução de venda de mercadoria adquirida ou recebida de terceiros",
    "2203": "Devolução de venda de produção do estabelecimento destinada à Zona Franca de Manaus",
    "2204": "Devolução de venda de mercadoria adquirida destinada à Zona Franca de Manaus",
    "2208": "Devolução de produção do estabelecimento remetida em transferência",
    "2209": "Devolução de mercadoria adquirida remetida em transferência",
    "2251": "Compra de energia elétrica para distribuição",
    "2252": "Compra de energia elétrica por estabelecimento industrial",
    "2253": "Compra de energia elétrica por estabelecimento comercial",
    "2254": "Compra de energia elétrica por estabelecimento prestador de serviço de transporte",
    "2255": "Compra de energia elétrica por estabelecimento prestador de serviço de comunicação",
    "2256": "Compra de energia elétrica por estabelecimento de produtor rural",
    "2257": "Compra de energia elétrica para consumo por demanda contratada",
    "2401": "Compra para industrialização em operação com mercadoria sujeita ao regime de ST",
    "2403": "Compra para comercialização em operação com mercadoria sujeita ao regime de ST",
    "2406": "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de ST",
    "2407": "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de ST",
    "2408": "Transferência para industrialização em operação com mercadoria sujeita ao regime de ST",
    "2409": "Transferência para comercialização em operação com mercadoria sujeita ao regime de ST",
    "2410": "Devolução de venda de mercadoria com ST",
    "2411": "Devolução de venda de mercadoria com ST em operação com mercadoria sujeita ao regime de ST",
    "2414": "Retorno de mercadoria para venda remetida para estabelecimentos em regime de ST",
    "2501": "Entrada de mercadoria recebida com fim específico de exportação",
    "2503": "Entrada decorrente de devolução de produto remetido com fim específico de exportação",
    "2504": "Entrada decorrente de devolução de mercadoria remetida para formação de lote de exportação",
    "2551": "Compra de bem para o ativo imobilizado",
    "2552": "Transferência de bem do ativo imobilizado",
    "2553": "Devolução de venda de bem do ativo imobilizado",
    "2554": "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento",
    "2555": "Entrada de bem do ativo imobilizado de terceiro remetido para uso no estabelecimento",
    "2556": "Compra de material para uso ou consumo",
    "2557": "Transferência de material para uso ou consumo",
    "2603": "Ressarcimento de ICMS retido por substituição tributária",
    "2651": "Compra de combustível para industrialização subsequente",
    "2652": "Compra de combustível para comercialização",
    "2653": "Compra de combustível para uso ou consumo",
    "2901": "Entrada para industrialização por encomenda",
    "2902": "Retorno de mercadoria remetida para industrialização por encomenda",
    "2903": "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo",
    "2904": "Retorno de remessa para venda fora do estabelecimento",
    "2905": "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral",
    "2906": "Retorno de mercadoria remetida para depósito fechado ou armazém geral",
    "2907": "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral",
    "2908": "Entrada de bem por conta de contrato de comodato",
    "2909": "Retorno de bem remetido por conta de contrato de comodato",
    "2910": "Entrada de bonificação, doação ou brinde",
    "2911": "Entrada de amostra grátis",
    "2912": "Entrada de mercadoria ou bem recebido para demonstração",
    "2913": "Retorno de mercadoria ou bem remetido para demonstração",
    "2914": "Retorno de mercadoria ou bem remetido para exposição ou feira",
    "2915": "Entrada de mercadoria ou bem recebido para conserto ou reparo",
    "2916": "Retorno de mercadoria ou bem remetido para conserto ou reparo",
    "2917": "Entrada de mercadoria recebida em consignação mercantil ou industrial",
    "2918": "Devolução de mercadoria remetida em consignação mercantil ou industrial",
    "2919": "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial remetida anteriormente em consignação",
    "2920": "Entrada de vasilhame ou sacaria",
    "2921": "Retorno de vasilhame ou sacaria",
    "2922": "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro",
    "2923": "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem",
    "2924": "Entrada para industrialização por conta e ordem do adquirente da mercadoria",
    "2925": "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente",
    "2933": "Aquisição de serviço tributado pelo ISSQN",
    "2949": "Outra entrada de mercadoria ou prestação de serviço não especificada",

    # ══════════════════════════════════════════════
    # ENTRADAS IMPORTAÇÃO (3xxx)
    # ══════════════════════════════════════════════
    "3101": "Compra para industrialização (importação)",
    "3102": "Compra para comercialização (importação)",
    "3126": "Compra para utilização na prestação de serviço sujeita ao ICMS",
    "3127": "Compra para industrialização sob o regime de drawback",
    "3128": "Compra para utilização na prestação de serviço sujeita ao ISSQN",
    "3201": "Devolução de venda de produção do estabelecimento (exportação)",
    "3202": "Devolução de venda de mercadoria adquirida (exportação)",
    "3211": "Devolução de venda de produção do estabelecimento sob o regime de drawback",
    "3251": "Compra de energia elétrica para distribuição (importação)",
    "3301": "Aquisição de serviço de comunicação para execução de serviço da mesma natureza (importação)",
    "3351": "Aquisição de serviço de transporte para execução de serviço da mesma natureza (importação)",
    "3551": "Compra de bem para o ativo imobilizado (importação)",
    "3556": "Compra de material para uso ou consumo (importação)",
    "3651": "Compra de combustível para industrialização subsequente (importação)",
    "3652": "Compra de combustível para comercialização (importação)",
    "3653": "Compra de combustível para uso ou consumo (importação)",
    "3930": "Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária",
    "3949": "Outra entrada de mercadoria ou prestação de serviço não especificada (importação)",

    # ══════════════════════════════════════════════
    # SAÍDAS ESTADUAIS (5xxx)
    # ══════════════════════════════════════════════
    "5101": "Venda de produção do estabelecimento",
    "5102": "Venda de mercadoria adquirida ou recebida de terceiros",
    "5103": "Venda de produção do estabelecimento efetuada fora do estabelecimento",
    "5104": "Venda de mercadoria adquirida efetuada fora do estabelecimento",
    "5105": "Venda de produção do estabelecimento que não deva por ele transitar",
    "5106": "Venda de mercadoria adquirida que não deva por ele transitar",
    "5109": "Venda de produção do estabelecimento destinada à Zona Franca de Manaus",
    "5110": "Venda de mercadoria adquirida destinada à Zona Franca de Manaus",
    "5111": "Venda de produção do estabelecimento remetida anteriormente em consignação industrial",
    "5112": "Venda de mercadoria adquirida remetida anteriormente em consignação mercantil",
    "5113": "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil",
    "5114": "Venda de mercadoria adquirida remetida anteriormente em consignação industrial",
    "5115": "Venda de mercadoria adquirida recebida anteriormente em consignação mercantil",
    "5116": "Venda de produção do estabelecimento originada de encomenda para entrega futura",
    "5117": "Venda de mercadoria adquirida originada de encomenda para entrega futura",
    "5118": "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente, em venda à ordem",
    "5119": "Venda de mercadoria adquirida entregue ao destinatário por conta e ordem do adquirente, em venda à ordem",
    "5120": "Venda de mercadoria adquirida entregue ao destinatário pelo vendedor remetente, em venda à ordem",
    "5122": "Venda de produção remetida para industrialização por conta e ordem do adquirente sem transitar pelo estabelecimento",
    "5123": "Venda de mercadoria adquirida remetida para industrialização por conta e ordem do adquirente",
    "5124": "Industrialização efetuada para outra empresa",
    "5125": "Industrialização efetuada para outra empresa quando a mercadoria foi remetida pelo fornecedor",
    "5151": "Transferência de produção do estabelecimento",
    "5152": "Transferência de mercadoria adquirida ou recebida de terceiros",
    "5153": "Transferência de energia elétrica para distribuição",
    "5155": "Transferência de produção do estabelecimento que não deva por ele transitar",
    "5156": "Transferência de mercadoria adquirida que não deva por ele transitar",
    "5201": "Devolução de compra para industrialização",
    "5202": "Devolução de compra para comercialização",
    "5205": "Anulação de valor relativo a aquisição de serviço de comunicação",
    "5206": "Anulação de valor relativo a aquisição de serviço de transporte",
    "5207": "Anulação de valor relativo a compra de energia elétrica",
    "5208": "Devolução de compra para utilização na prestação de serviço",
    "5209": "Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de ST",
    "5210": "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de ST",
    "5251": "Venda de energia elétrica para distribuição",
    "5252": "Venda de energia elétrica para estabelecimento industrial",
    "5253": "Venda de energia elétrica para estabelecimento comercial",
    "5301": "Prestação de serviço de comunicação para execução de serviço da mesma natureza",
    "5351": "Prestação de serviço de transporte para execução de serviço da mesma natureza",
    "5352": "Prestação de serviço de transporte a estabelecimento industrial",
    "5353": "Prestação de serviço de transporte a estabelecimento comercial",
    "5401": "Venda de produção do estabelecimento em operação com mercadoria sujeita ao regime de ST",
    "5402": "Venda de produção do estabelecimento de produto sujeito ao regime de ST, em operação entre contribuintes optantes pelo Simples Nacional",
    "5403": "Venda de mercadoria adquirida, sujeita ao regime de ST, em operação entre contribuintes optantes pelo Simples Nacional",
    "5405": "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de ST, na condição de contribuinte substituído",
    "5501": "Remessa de produção do estabelecimento com fim específico de exportação",
    "5502": "Remessa de mercadoria adquirida com fim específico de exportação",
    "5503": "Devolução de produto remetido com fim específico de exportação",
    "5551": "Venda de bem do ativo imobilizado",
    "5552": "Transferência de bem do ativo imobilizado",
    "5553": "Devolução de compra de bem para o ativo imobilizado",
    "5554": "Remessa de bem do ativo imobilizado para uso fora do estabelecimento",
    "5555": "Devolução de bem do ativo imobilizado de terceiro recebido para uso no estabelecimento",
    "5556": "Devolução de compra de material de uso ou consumo",
    "5557": "Transferência de material de uso ou consumo",
    "5601": "Transferência de crédito de ICMS acumulado",
    "5602": "Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa",
    "5603": "Ressarcimento de ICMS retido por substituição tributária",
    "5605": "Transferência de saldo devedor de ICMS de outro estabelecimento",
    "5651": "Venda de combustível ou lubrificante para industrialização subsequente",
    "5652": "Venda de combustível ou lubrificante para comercialização",
    "5653": "Venda de combustível ou lubrificante a consumidor ou usuário final",
    "5654": "Venda de combustível ou lubrificante para consumo em processo de industrialização",
    "5655": "Venda de combustível ou lubrificante para execução de serviço de transporte",
    "5656": "Venda de combustível ou lubrificante para execução de serviço de comunicação",
    "5657": "Remessa de combustível ou lubrificante para venda fora do estabelecimento",
    "5658": "Transferência de combustível ou lubrificante de produção do estabelecimento",
    "5659": "Transferência de combustível ou lubrificante adquirido ou recebido de terceiros",
    "5660": "Devolução de compra de combustível ou lubrificante para industrialização subsequente",
    "5661": "Devolução de compra de combustível ou lubrificante para comercialização",
    "5662": "Devolução de compra de combustível ou lubrificante para uso ou consumo",
    "5663": "Remessa para armazenagem de combustível",
    "5664": "Retorno de combustível recebido para armazenagem",
    "5665": "Retorno simbólico de combustível recebido para armazenagem",
    "5666": "Remessa por conta e ordem de terceiros de combustível recebido para armazenagem",
    "5667": "Venda de combustível a consumidor ou usuário final estabelecido em outra unidade da Federação",
    "5901": "Remessa para industrialização por encomenda",
    "5902": "Retorno de mercadoria utilizada na industrialização por encomenda",
    "5903": "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo",
    "5904": "Remessa para venda fora do estabelecimento",
    "5905": "Remessa para depósito fechado ou armazém geral",
    "5906": "Retorno de mercadoria depositada em depósito fechado ou armazém geral",
    "5907": "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral",
    "5908": "Remessa de bem por conta de contrato de comodato",
    "5909": "Retorno de bem recebido por conta de contrato de comodato",
    "5910": "Remessa em bonificação, doação ou brinde",
    "5911": "Remessa de amostra grátis",
    "5912": "Remessa de mercadoria ou bem para demonstração",
    "5913": "Retorno de mercadoria ou bem recebido para demonstração",
    "5914": "Remessa de mercadoria ou bem para exposição ou feira",
    "5915": "Remessa de mercadoria ou bem para conserto ou reparo",
    "5916": "Retorno de mercadoria ou bem recebido para conserto ou reparo",
    "5917": "Remessa de mercadoria em consignação mercantil ou industrial",
    "5918": "Devolução de mercadoria recebida em consignação mercantil ou industrial",
    "5919": "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial recebida anteriormente em consignação",
    "5920": "Remessa de vasilhame ou sacaria",
    "5921": "Devolução de vasilhame ou sacaria",
    "5922": "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura",
    "5923": "Remessa de mercadoria por conta e ordem de terceiros em venda à ordem",
    "5924": "Remessa para industrialização por conta e ordem do adquirente da mercadoria",
    "5925": "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente",
    "5926": "Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação",
    "5929": "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação de NF anteriormente emitida",
    "5933": "Prestação de serviço tributado pelo ISSQN",
    "5949": "Outra saída de mercadoria ou prestação de serviço não especificada",

    # ══════════════════════════════════════════════
    # SAÍDAS INTERESTADUAIS (6xxx)
    # ══════════════════════════════════════════════
    "6101": "Venda de produção do estabelecimento",
    "6102": "Venda de mercadoria adquirida ou recebida de terceiros",
    "6103": "Venda de produção do estabelecimento efetuada fora do estabelecimento",
    "6104": "Venda de mercadoria adquirida efetuada fora do estabelecimento",
    "6105": "Venda de produção do estabelecimento que não deva por ele transitar",
    "6106": "Venda de mercadoria adquirida que não deva por ele transitar",
    "6107": "Venda de produção do estabelecimento para não contribuinte",
    "6108": "Venda de mercadoria adquirida para não contribuinte",
    "6109": "Venda de produção do estabelecimento destinada à Zona Franca de Manaus",
    "6110": "Venda de mercadoria adquirida destinada à Zona Franca de Manaus",
    "6111": "Venda de produção remetida anteriormente em consignação industrial",
    "6112": "Venda de mercadoria remetida anteriormente em consignação mercantil",
    "6113": "Venda de produção remetida anteriormente em consignação mercantil",
    "6116": "Venda de produção originada de encomenda para entrega futura",
    "6117": "Venda de mercadoria adquirida originada de encomenda para entrega futura",
    "6118": "Venda de produção entregue ao destinatário por conta e ordem do adquirente, em venda à ordem",
    "6119": "Venda de mercadoria adquirida entregue ao destinatário por conta e ordem do adquirente, em venda à ordem",
    "6120": "Venda de mercadoria adquirida entregue ao destinatário pelo vendedor remetente, em venda à ordem",
    "6122": "Venda de produção remetida para industrialização por conta e ordem do adquirente",
    "6123": "Venda de mercadoria adquirida remetida para industrialização por conta e ordem do adquirente",
    "6124": "Industrialização efetuada para outra empresa",
    "6125": "Industrialização efetuada para outra empresa quando a mercadoria foi remetida pelo fornecedor",
    "6151": "Transferência de produção do estabelecimento",
    "6152": "Transferência de mercadoria adquirida ou recebida de terceiros",
    "6153": "Transferência de energia elétrica para distribuição",
    "6155": "Transferência de produção do estabelecimento que não deva por ele transitar",
    "6156": "Transferência de mercadoria adquirida que não deva por ele transitar",
    "6201": "Devolução de compra para industrialização",
    "6202": "Devolução de compra para comercialização",
    "6205": "Anulação de valor relativo a aquisição de serviço de comunicação",
    "6206": "Anulação de valor relativo a aquisição de serviço de transporte",
    "6207": "Anulação de valor relativo a compra de energia elétrica",
    "6208": "Devolução de compra para utilização na prestação de serviço",
    "6209": "Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de ST",
    "6210": "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de ST",
    "6401": "Venda de produção em operação com mercadoria sujeita ao regime de ST",
    "6403": "Venda de mercadoria adquirida sujeita ao regime de ST",
    "6404": "Venda de mercadoria sujeita ao regime de ST, cujo imposto já foi retido anteriormente",
    "6405": "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de ST, na condição de contribuinte substituído",
    "6501": "Remessa de produção do estabelecimento com fim específico de exportação",
    "6502": "Remessa de mercadoria adquirida com fim específico de exportação",
    "6503": "Devolução de produto remetido com fim específico de exportação",
    "6551": "Venda de bem do ativo imobilizado",
    "6552": "Transferência de bem do ativo imobilizado",
    "6553": "Devolução de compra de bem para o ativo imobilizado",
    "6556": "Devolução de compra de material de uso ou consumo",
    "6557": "Transferência de material de uso ou consumo",
    "6603": "Ressarcimento de ICMS retido por substituição tributária",
    "6651": "Venda de combustível ou lubrificante para industrialização subsequente",
    "6652": "Venda de combustível ou lubrificante para comercialização",
    "6653": "Venda de combustível ou lubrificante a consumidor ou usuário final",
    "6901": "Remessa para industrialização por encomenda",
    "6902": "Retorno de mercadoria utilizada na industrialização por encomenda",
    "6903": "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo",
    "6904": "Remessa para venda fora do estabelecimento",
    "6905": "Remessa para depósito fechado ou armazém geral",
    "6906": "Retorno de mercadoria depositada em depósito fechado ou armazém geral",
    "6907": "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral",
    "6908": "Remessa de bem por conta de contrato de comodato",
    "6909": "Retorno de bem recebido por conta de contrato de comodato",
    "6910": "Remessa em bonificação, doação ou brinde",
    "6911": "Remessa de amostra grátis",
    "6912": "Remessa de mercadoria ou bem para demonstração",
    "6913": "Retorno de mercadoria ou bem recebido para demonstração",
    "6914": "Remessa de mercadoria ou bem para exposição ou feira",
    "6915": "Remessa de mercadoria ou bem para conserto ou reparo",
    "6916": "Retorno de mercadoria ou bem recebido para conserto ou reparo",
    "6917": "Remessa de mercadoria em consignação mercantil ou industrial",
    "6918": "Devolução de mercadoria recebida em consignação mercantil ou industrial",
    "6920": "Remessa de vasilhame ou sacaria",
    "6921": "Devolução de vasilhame ou sacaria",
    "6922": "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura",
    "6923": "Remessa de mercadoria por conta e ordem de terceiros em venda à ordem",
    "6924": "Remessa para industrialização por conta e ordem do adquirente da mercadoria",
    "6925": "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente",
    "6929": "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação de NF anteriormente emitida",
    "6933": "Prestação de serviço tributado pelo ISSQN",
    "6949": "Outra saída de mercadoria ou prestação de serviço não especificada",

    # ══════════════════════════════════════════════
    # SAÍDAS EXPORTAÇÃO (7xxx)
    # ══════════════════════════════════════════════
    "7101": "Venda de produção do estabelecimento (exportação)",
    "7102": "Venda de mercadoria adquirida ou recebida de terceiros (exportação)",
    "7105": "Venda de produção do estabelecimento que não deva por ela transitar (exportação)",
    "7106": "Venda de mercadoria adquirida que não deva por ela transitar (exportação)",
    "7127": "Venda de produção do estabelecimento sob o regime de drawback",
    "7201": "Devolução de compra para industrialização (importação)",
    "7202": "Devolução de compra para comercialização (importação)",
    "7205": "Anulação de valor relativo a aquisição de serviço de comunicação (importação)",
    "7206": "Anulação de valor relativo a aquisição de serviço de transporte (importação)",
    "7207": "Anulação de valor relativo a compra de energia elétrica (importação)",
    "7251": "Venda de energia elétrica para o exterior",
    "7301": "Prestação de serviço de comunicação para o exterior",
    "7358": "Prestação de serviço de transporte — outros",
    "7501": "Exportação de mercadoria recebida com fim específico de exportação",
    "7551": "Venda de bem do ativo imobilizado",
    "7553": "Devolução de compra de bem para o ativo imobilizado (importação)",
    "7556": "Devolução de compra de material de uso ou consumo (importação)",
    "7651": "Venda de combustível ou lubrificante para industrialização subsequente",
    "7667": "Venda de combustível a consumidor ou usuário final",
    "7930": "Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária",
    "7949": "Outra saída de mercadoria ou prestação de serviço não especificada (exportação)",
}


def is_valid_cfop(code: str) -> bool:
    """Verifica se o CFOP existe na tabela."""
    return code in CFOP


def get_cfop_descricao(code: str) -> str | None:
    """Retorna a descrição do CFOP ou None se inválido."""
    return CFOP.get(code)


def cfop_direction(code: str) -> str | None:
    """Retorna 'entrada' ou 'saida' com base no primeiro dígito do CFOP.

    1xxx, 2xxx, 3xxx → entrada
    5xxx, 6xxx, 7xxx → saída
    """
    if not code or len(code) < 4 or not code[0].isdigit():
        return None
    return "entrada" if code[0] in ("1", "2", "3") else "saida"


def cfop_scope(code: str) -> str | None:
    """Retorna o escopo geográfico do CFOP.

    1xxx/5xxx → estadual
    2xxx/6xxx → interestadual
    3xxx/7xxx → exterior (importação/exportação)
    """
    if not code or len(code) < 4 or not code[0].isdigit():
        return None
    mapping = {
        "1": "estadual", "2": "interestadual", "3": "exterior",
        "5": "estadual", "6": "interestadual", "7": "exterior",
    }
    return mapping.get(code[0])


def cfop_is_devolucao(code: str) -> bool:
    """Verifica se o CFOP é uma devolução (faixas x2xx)."""
    if not code or len(code) < 4:
        return False
    return code[1] == "2"


def cfop_is_transferencia(code: str) -> bool:
    """Verifica se o CFOP é uma transferência (faixas x15x)."""
    if not code or len(code) < 4:
        return False
    return code[1:3] == "15"


def cfop_is_st(code: str) -> bool:
    """Verifica se o CFOP envolve substituição tributária (faixas x4xx)."""
    if not code or len(code) < 4:
        return False
    return code[1] == "4"
