"""cria tabela estoque

Revision ID: 5065442b792a
Revises: 
Create Date: 2025-05-16 07:14:36.631820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5065442b792a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.create_index(op.f('ix_estoque_nome'), 'estoque', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_nome'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    # ### end Alembic commands ###
